ARG RUBY_IMAGE_VERSION
ARG BASE_IMAGE=ruby:${RUBY_IMAGE_VERSION}-slim-buster
FROM ${BASE_IMAGE}

ENV LANG=C.UTF-8

RUN mkdir /home/app
WORKDIR /home/app

ENV GITHUB_REGISTRY_TOKEN ""

# ENV vars that danger cares about
ENV DANGER_GITHUB_API_TOKEN ""
ENV BUILDKITE ""
ENV BUILDKITE_REPO ""
ENV BUILDKITE_PULL_REQUEST ""
ENV BUILDKITE_BUILD_URL ""
