#!/bin/bash
set -euo pipefail

BUILDKITE_DANGER_SYSTEMS_LANGUAGE=${BUILDKITE_DANGER_SYSTEMS_LANGUAGE:-}
BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST:-}

# Return early if there’s no PR to comment against
if [[ -z "${BUILDKITE_PULL_REQUEST:-}" ]]; then
  echo "Skipping, no pull request"
  exit 0
fi;

if [[ -z "$BUILDKITE_DANGER_SYSTEMS_LANGUAGE" ]]; then
  # Ensure a language is specified
  echo "You must specify a language for danger to use"
  buildkite-agent annotate --style error
  exit 1
elif [ "$BUILDKITE_DANGER_SYSTEMS_LANGUAGE" == "js" ]; then
  bin/danger_js
elif [ "$BUILDKITE_DANGER_SYSTEMS_LANGUAGE" == "ruby" ]; then
  bin/danger_ruby
fi;
